[build]
  publish = "_site"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"            # 20도 OK, 18은 X (cross-env@10이 Node>=20 요구)
  TZ = "Asia/Seoul"              # 빌드 시 날짜·시간 계산 KST 고정

[functions]
  directory = "netlify/functions"

# ✅ Netlify Scheduled Functions (UTC 기준)
#   예) 매일 00:10 KST에 실행하려면 15:10 UTC
[[scheduled.functions]]
  name = "scheduler"
  cron = "10 15 * * *"

# ✅ SPA 라우팅
# Admin(CMS) 우선 지정 → 나머지 전부 index.html로
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200