[build]
  publish = "_site"  # ← 기존 "_site"에서 "_public"으로 변경
  command = "npx @11ty/eleventy"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200