backend:
  name: git-gateway
  branch: main
  repo: 3t1sy1fa/SPORTS-monologue

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "글"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "카테고리", name: "category", widget: "select", options: ["선수 분석", "경기 분석", "스포츠 경영"] }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "요약", name: "excerpt", widget: "text",required: false }
      - label: "주제"
        name: "topic"
        widget: "select"
        required: false
        options: ["리그 경영 전략", "브랜드/팬덤", "굿즈,상품화 전략", "리스크,안정성 전략", "팬 경험 혁신", "기타"]
        conditional:
          field: "category"
          value: "스포츠 경영"
      - { label: "본문", name: "body", widget: "markdown" }

  - name: "log"
    label: "log"
    folder: "src/log"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "카테고리", name: "category", widget: "select", options: ["사이트 제작", "사이트 운영", "경영", "분석", "기타"] }
      - { label: "설명", name: "description", widget: "text" }
      - { label: "레이아웃", name: "layout", widget: "hidden", default: "post.njk" }
      - { label: "본문", name: "body", widget: "markdown" }

  - name: "teamAnalysis"
    label: "구단 분석"
    folder: "src/teams-analysis"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
    - { label: "제목", name: "title", widget: "string" }
    - { label: "작성일", name: "date", widget: "datetime" }
    - { label: "레이아웃", name: "layout", widget: "hidden", default: "team-layout.njk" }
    - { label: "설명", name: "description", widget: "text" }
    - label: "카테고리"
      name: "category"
      widget: "select"
      options:
        - { label: "LG 트윈스", value: "lg" }
        - { label: "두산 베어스", value: "doosan" }
        - { label: "키움 히어로즈", value: "kiwoom" }
        - { label: "롯데 자이언츠", value: "lotte" }
        - { label: "한화 이글스", value: "hanwha" }
        - { label: "삼성 라이온즈", value: "samsung" }
        - { label: "NC 다이노스", value: "nc" }
        - { label: "KIA 타이거즈", value: "kia" }
        - { label: "KT 위즈", value: "kt" }
        - { label: "SSG 랜더스", value: "ssg" }
    - {
        label: "팀 CSS",
        name: "teamCss",
        widget: "select",
        options: [
          "team-lg.css", "team-doosan.css", "team-kiwoom.css", "team-lotte.css",
          "team-hanwha.css", "team-samsung.css", "team-nc.css", "team-kia.css",
          "team-kt.css", "team-ssg.css"
        ]
      }
    - { label: "본문", name: "body", widget: "markdown" }