backend:
  name: git-gateway
  branch: main
  repo: 3t1sy1fa/SPORTS-monologue

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "글"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "카테고리", name: "category", widget: "select", options: ["선수 분석", "경기 분석", "구단 분석"] }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "요약", name: "excerpt", widget: "text" }
      - { label: "본문", name: "body", widget: "markdown" }