backend:
  name: git-gateway
  branch: main  # GitHub default branch

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "분석글"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "카테고리", name: "category", widget: "select", options: ["선수 분석", "경기 분석", "구단 분석"] }
      - { label: "본문", name: "body", widget: "markdown" }
