backend:
  name: git-gateway
  branch: main  # 또는 master

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "블로그 글"
    folder: "data/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "본문", name: "body", widget: "markdown" }
      