backend:
  name: git-gateway
  branch: main
  repo: 3t1sy1fa/SPORTS-monologue

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "글"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "카테고리", name: "category", widget: "select", options: ["선수 분석", "경기 분석", "구단 분석"] }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "요약", name: "excerpt", widget: "text" }
      - { label: "본문", name: "body", widget: "markdown" }


      collections:
  - name: "lab"
    label: "Lab"
    folder: "src/lab"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "lab/{{slug}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "카테고리", name: "category", widget: "select", options: ["디자인", "코드", "기획", "스케치", "기타"] }
      - { label: "설명", name: "description", widget: "text" }
      - { label: "본문", name: "body", widget: "markdown" }